version: '3'
services: 
    ubuntu-desktop-lxde-vnc:
        container_name: ubuntu-desktop-lxde-vnc
        build:
            context: ./docker/ubuntu
        ports:
            - "6080:80"
        volumes:
            - "./src:/src"
        working_dir: /src
        tty: true